### ISSUE TITLE
gt.MLA_Clean()

### ISSUE THREAD

**Issue by jke513** [gptune/GPTune#5]
Hi, 

I am trying to run TLA code. 
https://github.com/gptune/GPTune/blob/master/examples/GPTune-Demo/demo_TLA.py#L255 
`AttributeError: 'GPTune' object has no attribute 'MLA_Clean' `
Is MLA_Clean() available in GPTune?? 

Thank you for your help.

**Comment by younghyunc** [comment]
Hi,

Thank you for asking. The MLA_Clean function was previously used to differentiate between MLA that does not load historical data and MLA that loads historical data. The MLA_Clean function is now removed. Instead, users can invoke MLA with no loading by using meta data options (e.g. "load_func_eval": "no"). The issue was because the GPTune-Demo TLA example code was still using the old interface.

I have updated the GPTune-Demo TLA example code and the TLA experiment script. This will use the new interface.
https://github.com/gptune/GPTune/commit/c56aeab92d28d7e4d6b81836aa8d94761fcd5463
https://github.com/gptune/GPTune/commit/870406bf098cbf1076de3a6843cc8777d56f4c6c

Could you checkout the latest version and try the example again? Thank you!

**Comment by younghyunc** [comment]
Hi @jke513,

In the commit https://github.com/gptune/GPTune/commit/c56aeab92d28d7e4d6b81836aa8d94761fcd5463, I accidentally disabled the default db data load option.

So, to use a more stable version of GPTune, please also apply this commit https://github.com/gptune/GPTune/commit/b3075688dca2c67bd2e7d4f264d67b9989da6f37. Running a single "git pull" command will be enough. Thank you!

**Comment by jke513** [comment]
Thank you for the edit.
